# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths /home/festus/Documents/vivado/svm_online [current_fileset]
read_vhdl {
  /home/festus/Documents/vivado/svm_online/svm_online.srcs/sources_1/new/comparing.vhd
  /home/festus/Documents/vivado/svm_online/svm_online.srcs/sources_1/new/classify.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/festus/Documents/vivado/svm_online/svm_online.data/wt [current_project]
set_property parent.project_dir /home/festus/Documents/vivado/svm_online [current_project]
synth_design -top classify -part xc7z010clg400-1
write_checkpoint classify.dcp
report_utilization -file classify_utilization_synth.rpt -pb classify_utilization_synth.pb
